//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyUniverse.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrazyUniverse.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was fed. Current satiety: {1}.
        /// </summary>
        public static string Action_AnimalFed {
            get {
                return ResourceManager.GetString("Action_AnimalFed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already full (100/100) and cannot eat more!.
        /// </summary>
        public static string Action_FeedAlreadyFull {
            get {
                return ResourceManager.GetString("Action_FeedAlreadyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was fed. Current satiety: {1}/100..
        /// </summary>
        public static string Action_FeedSuccess {
            get {
                return ResourceManager.GetString("Action_FeedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the honey badger scales a tree like it owes him money and raids the beehive. (Current Satiety: {1}).
        /// </summary>
        public static string Action_HoneyBadgerClimb {
            get {
                return ResourceManager.GetString("Action_HoneyBadgerClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the honey badger is stuffed with honey and has decided that today nothing matters. (Current Satiety: {1}).
        /// </summary>
        public static string Action_HoneyBadgerCrazyLow {
            get {
                return ResourceManager.GetString("Action_HoneyBadgerCrazyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the honey badger lets out a furious growl, and the entire zoo suddenly remembers who is in charge! (Current Satiety: {1}).
        /// </summary>
        public static string Action_HoneyBadgerCrazyNormal {
            get {
                return ResourceManager.GetString("Action_HoneyBadgerCrazyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the honey badger growls so fiercely that even the lions pretend not to hear it! (Current Satiety: {1}).
        /// </summary>
        public static string Action_HoneyBadgerMakeSound {
            get {
                return ResourceManager.GetString("Action_HoneyBadgerMakeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the honey badger runs at full speed straight toward trouble, because running away is not in its vocabulary. (Current Satiety: {1}).
        /// </summary>
        public static string Action_HoneyBadgerRun {
            get {
                return ResourceManager.GetString("Action_HoneyBadgerRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the honey badger swims across the river out of pure spite. (Current Satiety: {1}).
        /// </summary>
        public static string Action_HoneyBadgerSwim {
            get {
                return ResourceManager.GetString("Action_HoneyBadgerSwim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the lion lets out a weak, tired grumble. (Current Satiety: {1}).
        /// </summary>
        public static string Action_LionCrazyLow {
            get {
                return ResourceManager.GetString("Action_LionCrazyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the lion roars so loud that the whole zoo shakes! (Current Satiety: {1}).
        /// </summary>
        public static string Action_LionCrazyNormal {
            get {
                return ResourceManager.GetString("Action_LionCrazyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the lion lets out a deep, majestic roar! (Current Satiety: {1}).
        /// </summary>
        public static string Action_LionMakeSound {
            get {
                return ResourceManager.GetString("Action_LionMakeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the monkey is too tired to throw anything and sits quietly. (Current Satiety: {1}).
        /// </summary>
        public static string Action_MonkeyCrazyLow {
            get {
                return ResourceManager.GetString("Action_MonkeyCrazyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the monkey excitedly throws a banana at the visitors! (Current Satiety: {1}).
        /// </summary>
        public static string Action_MonkeyCrazyNormal {
            get {
                return ResourceManager.GetString("Action_MonkeyCrazyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the monkey jumps high from branch to branch! (Current Satiety: {1}).
        /// </summary>
        public static string Action_MonkeyJump {
            get {
                return ResourceManager.GetString("Action_MonkeyJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the monkey chatters loudly: &apos;Ooh-ooh, aah-aah!&apos; (Current Satiety: {1}).
        /// </summary>
        public static string Action_MonkeyMakeSound {
            get {
                return ResourceManager.GetString("Action_MonkeyMakeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the penguin is too exhausted and sluggishly slides on the ice! (Current Satiety: {1}).
        /// </summary>
        public static string Action_PenguinCrazyLow {
            get {
                return ResourceManager.GetString("Action_PenguinCrazyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the penguin enthusiastically slides on its belly across the ice! (Current Satiety: {1}).
        /// </summary>
        public static string Action_PenguinCrazyNormal {
            get {
                return ResourceManager.GetString("Action_PenguinCrazyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the penguin swims gracefully, covering {1} meters through the cold water! (Current Satiety: {2}).
        /// </summary>
        public static string Action_PenguinSwim {
            get {
                return ResourceManager.GetString("Action_PenguinSwim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tiny, furious legend who does not care. Hungry? Picks a fight with a lion. Full? Still picks a fight, but with style..
        /// </summary>
        public static string Desc_HoneyBadgerDescription {
            get {
                return ResourceManager.GetString("Desc_HoneyBadgerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dramatic king of the concrete jungle suffering from existential dread and chronic hair gel addiction. Refuses to roar unless the echo sounds cool..
        /// </summary>
        public static string Desc_LionDescription {
            get {
                return ResourceManager.GetString("Desc_LionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A professional chaos enthusiast who believes keyboards are edible and physics is optional. Constantly plots to steal the zookeeper&apos;s keys and throw banana peels..
        /// </summary>
        public static string Desc_MonkeyDescription {
            get {
                return ResourceManager.GetString("Desc_MonkeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An elite tactical spy trapped in a tuxedo, plotting a global ice-cube robbery. Dances wildly on the ice whenever nobody is watching..
        /// </summary>
        public static string Desc_PenguinDescription {
            get {
                return ResourceManager.GetString("Desc_PenguinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal name is required..
        /// </summary>
        public static string Err_AnimalNameRequired {
            get {
                return ResourceManager.GetString("Err_AnimalNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input! Distance must be greater than zero. {0} stays put, state remains unchanged..
        /// </summary>
        public static string Err_InvalidDistance {
            get {
                return ResourceManager.GetString("Err_InvalidDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added a new animal: {0}.
        /// </summary>
        public static string Log_AddedAnimal {
            get {
                return ResourceManager.GetString("Log_AddedAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [System] Language changed to: {0}.
        /// </summary>
        public static string Log_LangChanged {
            get {
                return ResourceManager.GetString("Log_LangChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Please select an animal to perform a crazy action..
        /// </summary>
        public static string Log_NoAnimalCrazy {
            get {
                return ResourceManager.GetString("Log_NoAnimalCrazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Please select an animal to feed..
        /// </summary>
        public static string Log_NoAnimalFeed {
            get {
                return ResourceManager.GetString("Log_NoAnimalFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: No animal selected for removal..
        /// </summary>
        public static string Log_NoAnimalRemove {
            get {
                return ResourceManager.GetString("Log_NoAnimalRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} removed from the zoo..
        /// </summary>
        public static string Log_RemovedAnimal {
            get {
                return ResourceManager.GetString("Log_RemovedAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoo initialized with default animals..
        /// </summary>
        public static string Log_ZooInit {
            get {
                return ResourceManager.GetString("Log_ZooInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honey Badger.
        /// </summary>
        public static string UI_HoneyBadgerTypeName {
            get {
                return ResourceManager.GetString("UI_HoneyBadgerTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lion.
        /// </summary>
        public static string UI_LionTypeName {
            get {
                return ResourceManager.GetString("UI_LionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monkey.
        /// </summary>
        public static string UI_MonkeyTypeName {
            get {
                return ResourceManager.GetString("UI_MonkeyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penguin.
        /// </summary>
        public static string UI_PenguinTypeName {
            get {
                return ResourceManager.GetString("UI_PenguinTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total animals: {0}.
        /// </summary>
        public static string UI_TotalAnimals {
            get {
                return ResourceManager.GetString("UI_TotalAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoo Population: {0}.
        /// </summary>
        public static string UI_ZooPopulation {
            get {
                return ResourceManager.GetString("UI_ZooPopulation", resourceCulture);
            }
        }
    }
}
