//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyUniverse.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrazyUniverse.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} was fed. Current satiety: {1}.
        /// </summary>
        public static string Action_AnimalFed {
            get {
                return ResourceManager.GetString("Action_AnimalFed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is already full (100/100) and cannot eat more!.
        /// </summary>
        public static string Action_FeedAlreadyFull {
            get {
                return ResourceManager.GetString("Action_FeedAlreadyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} was fed. Current satiety: {1}/100..
        /// </summary>
        public static string Action_FeedSuccess {
            get {
                return ResourceManager.GetString("Action_FeedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} the lion lets out a weak, tired grumble. (Current Satiety: {1}).
        /// </summary>
        public static string Action_LionCrazyLow {
            get {
                return ResourceManager.GetString("Action_LionCrazyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} the lion roars so loud that the whole zoo shakes! (Current Satiety: {1}).
        /// </summary>
        public static string Action_LionCrazyNormal {
            get {
                return ResourceManager.GetString("Action_LionCrazyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} the lion lets out a deep, majestic roar! (Current Satiety: {1}).
        /// </summary>
        public static string Action_LionMakeSound {
            get {
                return ResourceManager.GetString("Action_LionMakeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} the monkey is too tired to throw anything and sits quietly. (Current Satiety: {1}).
        /// </summary>
        public static string Action_MonkeyCrazyLow {
            get {
                return ResourceManager.GetString("Action_MonkeyCrazyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} the monkey excitedly throws a banana at the visitors! (Current Satiety: {1}).
        /// </summary>
        public static string Action_MonkeyCrazyNormal {
            get {
                return ResourceManager.GetString("Action_MonkeyCrazyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} the monkey jumps high from branch to branch! (Current Satiety: {1}).
        /// </summary>
        public static string Action_MonkeyJump {
            get {
                return ResourceManager.GetString("Action_MonkeyJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} the monkey chatters loudly: &apos;Ooh-ooh, aah-aah!&apos; (Current Satiety: {1}).
        /// </summary>
        public static string Action_MonkeyMakeSound {
            get {
                return ResourceManager.GetString("Action_MonkeyMakeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} the penguin is too exhausted and sluggishly slides on the ice! (Current Satiety: {1}).
        /// </summary>
        public static string Action_PenguinCrazyLow {
            get {
                return ResourceManager.GetString("Action_PenguinCrazyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} the penguin enthusiastically slides on its belly across the ice! (Current Satiety: {1}).
        /// </summary>
        public static string Action_PenguinCrazyNormal {
            get {
                return ResourceManager.GetString("Action_PenguinCrazyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} the penguin swims gracefully, covering {1} meters through the cold water! (Current Satiety: {2}).
        /// </summary>
        public static string Action_PenguinSwim {
            get {
                return ResourceManager.GetString("Action_PenguinSwim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A dramatic king of the concrete jungle suffering from existential dread and chronic hair gel addiction. Refuses to roar unless the echo sounds cool..
        /// </summary>
        public static string Desc_LionDescription {
            get {
                return ResourceManager.GetString("Desc_LionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A professional chaos enthusiast who believes keyboards are edible and physics is optional. Constantly plots to steal the zookeeper&apos;s keys and throw banana peels..
        /// </summary>
        public static string Desc_MonkeyDescription {
            get {
                return ResourceManager.GetString("Desc_MonkeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An elite tactical spy trapped in a tuxedo, plotting a global ice-cube robbery. Dances wildly on the ice whenever nobody is watching..
        /// </summary>
        public static string Desc_PenguinDescription {
            get {
                return ResourceManager.GetString("Desc_PenguinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Animal name is required..
        /// </summary>
        public static string Err_AnimalNameRequired {
            get {
                return ResourceManager.GetString("Err_AnimalNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid input! Distance must be greater than zero. {0} stays put, state remains unchanged..
        /// </summary>
        public static string Err_InvalidDistance {
            get {
                return ResourceManager.GetString("Err_InvalidDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Added a new animal: {0}.
        /// </summary>
        public static string Log_AddedAnimal {
            get {
                return ResourceManager.GetString("Log_AddedAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [System] Language changed to: {0}.
        /// </summary>
        public static string Log_LangChanged {
            get {
                return ResourceManager.GetString("Log_LangChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning: Please select an animal to perform a crazy action..
        /// </summary>
        public static string Log_NoAnimalCrazy {
            get {
                return ResourceManager.GetString("Log_NoAnimalCrazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning: Please select an animal to feed..
        /// </summary>
        public static string Log_NoAnimalFeed {
            get {
                return ResourceManager.GetString("Log_NoAnimalFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning: No animal selected for removal..
        /// </summary>
        public static string Log_NoAnimalRemove {
            get {
                return ResourceManager.GetString("Log_NoAnimalRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} removed from the zoo..
        /// </summary>
        public static string Log_RemovedAnimal {
            get {
                return ResourceManager.GetString("Log_RemovedAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoo initialized with default animals..
        /// </summary>
        public static string Log_ZooInit {
            get {
                return ResourceManager.GetString("Log_ZooInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lion.
        /// </summary>
        public static string UI_LionTypeName {
            get {
                return ResourceManager.GetString("UI_LionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monkey.
        /// </summary>
        public static string UI_MonkeyTypeName {
            get {
                return ResourceManager.GetString("UI_MonkeyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Penguin.
        /// </summary>
        public static string UI_PenguinTypeName {
            get {
                return ResourceManager.GetString("UI_PenguinTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total animals: {0}.
        /// </summary>
        public static string UI_TotalAnimals {
            get {
                return ResourceManager.GetString("UI_TotalAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoo Population: {0}.
        /// </summary>
        public static string UI_ZooPopulation {
            get {
                return ResourceManager.GetString("UI_ZooPopulation", resourceCulture);
            }
        }
    }
}
